import React from 'react';
import { 
  ShieldCheck, 
  ShieldAlert, 
  ShieldX, 
  Download, 
  Scale, 
  Send,
  CheckCircle2,
  AlertTriangle,
  Info
} from 'lucide-react';
import { cn } from '../lib/utils';
import { motion, AnimatePresence } from 'motion/react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import axios from 'axios';

interface AnalysisResultProps {
  result: {
    category: string;
    riskScore: number;
    confidence: number;
    detectedIssues: string[];
    matchedSignals?: string[];
    explanation?: string;
    recommendation: string;
    type: string;
    mode: string;
    input: string;
    textInterpretation?: string;
    visualInterpretation?: string;
  };
  onClose?: () => void;
}

export default function AnalysisResult({ result, onClose }: AnalysisResultProps) {
  const [showModal, setShowModal] = React.useState<{ type: 'FIR' | 'Notice' | null, message: string }>({ type: null, message: '' });

  const getSeverityColor = (category: string) => {
    switch (category) {
      case 'Safe': return 'text-gov-success bg-emerald-50 border-emerald-100';
      case 'Low Risk': return 'text-gov-blue bg-blue-50 border-blue-100';
      case 'Suspicious': return 'text-gov-warning bg-amber-50 border-amber-100';
      case 'Harmful': return 'text-orange-600 bg-orange-50 border-orange-100';
      case 'Critical': return 'text-gov-danger bg-rose-50 border-rose-100';
      default: return 'text-gov-text-muted bg-slate-50 border-slate-200';
    }
  };

  const getIcon = (category: string) => {
    if (category === 'Safe') return <ShieldCheck className="w-8 h-8 text-gov-success" />;
    if (category === 'Critical' || category === 'Harmful') return <ShieldX className="w-8 h-8 text-gov-danger" />;
    return <ShieldAlert className="w-8 h-8 text-gov-warning" />;
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();
    
    doc.setFontSize(22);
    doc.setTextColor(11, 31, 58);
    doc.text('PSHM-DSS Analysis Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(107, 114, 128);
    doc.text(`Generated on: ${timestamp}`, 105, 28, { align: 'center' });
    
    doc.setDrawColor(229, 231, 235);
    doc.line(20, 35, 190, 35);

    const data = [
      ['Analysis Type', result.type],
      ['Analysis Mode', result.mode],
      ['Risk Category', result.category],
      ['Risk Score', `${result.riskScore}%`],
      ['Confidence', `${result.confidence}%`],
      ['Input Summary', result.input.substring(0, 100) + (result.input.length > 100 ? '...' : '')],
      ['Detected Issues', result.detectedIssues.join(', ') || 'None'],
      ['Recommendation', result.recommendation]
    ];

    autoTable(doc, {
      startY: 45,
      head: [['Field', 'Details']],
      body: data,
      theme: 'striped',
      headStyles: { fillColor: [11, 31, 58] },
    });

    doc.setFontSize(12);
    doc.text('Detailed Explanation:', 20, (doc as any).lastAutoTable.finalY + 15);
    doc.setFontSize(10);
    const splitText = doc.splitTextToSize(result.explanation || result.textInterpretation || 'N/A', 170);
    doc.text(splitText, 20, (doc as any).lastAutoTable.finalY + 22);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('This is a demo report generated by PSHM-DSS. For official use only.', 105, 285, { align: 'center' });

    doc.save(`Analysis_Report_${Date.now()}.pdf`);
  };

  const handleAction = async (type: 'FIR' | 'Notice') => {
    try {
      const endpoint = type === 'FIR' ? '/api/action/fir' : '/api/action/notice';
      const res = await axios.post(endpoint);
      setShowModal({ type, message: res.data.message });
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="mt-8 glass-card rounded-2xl overflow-hidden"
    >
      <div className="p-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-xl bg-white shadow-sm border border-slate-100">
              {getIcon(result.category)}
            </div>
            <div>
              <h3 className="text-2xl font-bold text-slate-900">Analysis Results</h3>
              <p className="text-slate-500 text-sm">Mode: {result.mode} | Type: {result.type}</p>
            </div>
          </div>
          <div className={cn("px-6 py-2 rounded-full border font-bold text-lg", getSeverityColor(result.category))}>
            {result.category}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="p-6 rounded-xl bg-slate-50 border border-slate-100">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Risk Score</p>
            <div className="flex items-end gap-2">
              <span className="text-4xl font-bold text-slate-900">{result.riskScore}%</span>
              <div className="flex-1 h-2 bg-slate-200 rounded-full mb-2 overflow-hidden">
                <div 
                  className={cn("h-full transition-all duration-1000", result.riskScore > 70 ? "bg-red-500" : result.riskScore > 40 ? "bg-yellow-500" : "bg-green-500")}
                  style={{ width: `${result.riskScore}%` }}
                />
              </div>
            </div>
          </div>
          <div className="p-6 rounded-xl bg-slate-50 border border-slate-100">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Confidence</p>
            <span className="text-4xl font-bold text-slate-900">{result.confidence}%</span>
          </div>
          <div className="p-6 rounded-xl bg-slate-50 border border-slate-100">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Issues Detected</p>
            <span className="text-4xl font-bold text-slate-900">{result.detectedIssues.length}</span>
          </div>
        </div>

        <div className="space-y-6">
          <section>
            <h4 className="flex items-center gap-2 font-bold text-slate-800 mb-3">
              <Info className="w-4 h-4 text-gov-blue" />
              Interpretation & Findings
            </h4>
            <div className="p-4 rounded-xl bg-white border border-slate-200 text-slate-700 leading-relaxed">
              {result.explanation || result.textInterpretation || "No detailed interpretation available."}
            </div>
          </section>

          {result.detectedIssues.length > 0 && (
            <section>
              <h4 className="flex items-center gap-2 font-bold text-slate-800 mb-3">
                <AlertTriangle className="w-4 h-4 text-orange-500" />
                Detected Signals
              </h4>
              <div className="flex flex-wrap gap-2">
                {result.detectedIssues.map((issue, i) => (
                  <span key={i} className="px-3 py-1 rounded-lg bg-red-50 text-red-700 text-sm font-medium border border-red-100">
                    {issue}
                  </span>
                ))}
                {result.matchedSignals?.map((signal, i) => (
                  <span key={`sig-${i}`} className="px-3 py-1 rounded-lg bg-slate-100 text-slate-600 text-sm border border-slate-200">
                    {signal}
                  </span>
                ))}
              </div>
            </section>
          )}

          <section>
            <h4 className="flex items-center gap-2 font-bold text-slate-800 mb-3">
              <CheckCircle2 className="w-4 h-4 text-green-500" />
              Recommended Action
            </h4>
            <div className="p-4 rounded-xl bg-green-50 border border-green-100 text-green-800 font-medium">
              {result.recommendation}
            </div>
          </section>
        </div>

        <div className="mt-10 pt-8 border-t border-gov-border flex flex-wrap gap-4">
          <button 
            onClick={downloadPDF}
            className="btn-primary flex items-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download PDF Report
          </button>
          <button 
            onClick={() => handleAction('FIR')}
            className="btn-secondary text-gov-danger border-gov-danger hover:bg-rose-50 flex items-center gap-2"
          >
            <Scale className="w-5 h-5" />
            File FIR
          </button>
          <button 
            onClick={() => handleAction('Notice')}
            className="btn-secondary text-gov-warning border-gov-warning hover:bg-amber-50 flex items-center gap-2"
          >
            <Send className="w-5 h-5" />
            Send Notice
          </button>
        </div>
      </div>

      {/* Demo Modal */}
      <AnimatePresence>
        {showModal.type && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <motion.div 
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-white rounded-2xl p-8 max-w-md w-full shadow-2xl text-center"
            >
              <div className={cn(
                "w-20 h-20 rounded-full mx-auto flex items-center justify-center mb-6",
                showModal.type === 'FIR' ? "bg-red-100 text-red-600" : "bg-orange-100 text-orange-600"
              )}>
                {showModal.type === 'FIR' ? <Scale className="w-10 h-10" /> : <Send className="w-10 h-10" />}
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">{showModal.message}</h3>
              <p className="text-slate-500 mb-8">This action has been recorded in the system logs for demonstration purposes.</p>
              <button 
                onClick={() => setShowModal({ type: null, message: '' })}
                className="w-full py-3 bg-slate-900 text-white rounded-xl font-bold hover:bg-slate-800 transition-all"
              >
                Acknowledge
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
